### ISSUE TITLE
caddy proxy for docker

### ISSUE THREAD

**Issue by gedw99** [MightyMoud/sidekick#40]
if we can do this with caddy then bonus.

caddy has a lot of extra things that trawl does not via its plugins that give it super powers ..

https://github.com/lucaslorentz/caddy-docker-proxy

I know we have Traefik, but I have used this one before.

I think there are better examples out there too

**Comment by MightyMoud** [comment]
What kind of plugins that Caddy has that Traefik doesn't? I didn't spend much time on it but I did see Traefik has lots of plugins already

**Comment by hlongvu** [comment]
+1 for caddy
or let it be an option to choose between caddy and traefik

**Comment by MightyMoud** [comment]
Having a choice will mean I would have to introduce much more complexity to other commands so that's no good.

I'm happy to move Sidekick to Caddy if it's better. 
Can someone just articulate why Caddy is better than Traefik in details? maybe share a link to some discussion or something? Or has any of you used Traefik to its full potential before and decided to switch to Caddy?

**Comment by MightyMoud** [comment]
just for your info, I'm looking into this. I think Sidekick is stable enough now to attend to those things. 

will keep this open for now

**Comment by suciuvlad** [comment]
+1 for keeping Traefik.

**Comment by MightyMoud** [comment]
Yeah I looked into this btw. 
Traefik comes with out of the box integration with Prometheus that works very nicely. 

That part is essential for my future vision. Also turns out caddy is quite slow... https://www.youtube.com/watch?v=N5PAU-vYrN8
I know that is nginx but yeah not very impressed with Caddy anymore tbh. Hope he can compare caddy with Traefik at some point soon.
